print("statement")
print(a)
#print(*objects, sep=' ', end='\n', file=sys.stdout, flush=False)
print('The value of x is {} and y is {}'.format(x,y))
print('Hello {name}, {greeting}'.format(greeting = 'Goodmorning', name = 'John'))
num = input('Enter a number: ')
